name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Install Goose
        run:  go install github.com/pressly/goose/v3/cmd/goose@latest
      - name: Build App
        run: ./scripts/buildprod.sh

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'
      
      - name: Use GCloud CLI
        run: gcloud info

      - name: Build and Submit to Google Cloud
        run: gcloud builds submit --tag europe-west10-docker.pkg.dev/notely-465519/notely-ar-repo/notely .

      - name: Run Migrations
        run: ./scripts/migrateup.sh

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image europe-west10-docker.pkg.dev/notely-465519/notely-ar-repo/notely:latest --region europe-west1 --allow-unauthenticated --project notely-465519 --max-instances=4